tasks = {
    "I-FP1-R960": {
        "media_type": "image",
        "data": "configs/data/image_example.yaml",
        "global_bsz": 256,
        "micro_bsz": 8,
        "image_size": 256,
        "max_frames": None,
        "target_fps": None,
        "snr_type": "uniform",
        "time_shift": 1,
        "task_ratio": 4,
        "patch_size": 2,
        "f_patch_size": 1,
        "unbind_temporal": False,
        "num_workers": 3,
    },
    "V-FP1-f8F32R256": {
        "media_type": "video",
        "data": "configs/data/video_example.yaml",
        "global_bsz": 256,
        "micro_bsz": 8,
        "image_size": 256,
        "max_frames": 32,
        "target_fps": 8,
        "snr_type": "uniform",
        "time_shift": 2,
        "task_ratio": 4,
        "patch_size": 2,
        "f_patch_size": 1,
        "unbind_temporal": False,
        "num_workers": 3,
    },
    "V-FP2-f8F32R256": {
        "media_type": "video",
        "data": "configs/data/video_example.yaml",
        "global_bsz": 256,
        "micro_bsz": 8,
        "image_size": 256,
        "max_frames": 32,
        "target_fps": 8,
        "snr_type": "uniform",
        "time_shift": 4,
        "task_ratio": 4,
        "patch_size": 2,
        "f_patch_size": 2,
        "unbind_temporal": False,
        "num_workers": 3,
    },
    "V-FP2P4-f8F32R256": {
        "media_type": "video",
        "data": "configs/data/video_example.yaml",
        "global_bsz": 256,
        "micro_bsz": 8,
        "image_size": 256,
        "max_frames": 32,
        "target_fps": 8,
        "snr_type": "uniform",
        "time_shift": 8,
        "task_ratio": 4,
        "patch_size": 4,
        "f_patch_size": 2,
        "unbind_temporal": False,
        "num_workers": 3,
    },
}
